#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color=0xffb4befe
	inactive_color=0x33b4befe
    # 0x -> means hex
    # ff -> alpha value (00 to ff) opacity
    # b4befe -> color code (rgb)
)

borders "${options[@]}"
